#sign
#彩蛋
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ function media/egg
#签到
scoreboard players add @a sign_in 0
scoreboard players add @a[scores={sign_in=0..1,temp=456,level=1..2}] sign_inicon 10
scoreboard players add @a[scores={sign_in=0..1,temp=456,level=3..4}] sign_inicon 15
scoreboard players add @a[scores={sign_in=0..1,temp=456,level=5..6}] sign_inicon 20
scoreboard players add @a[scores={sign_in=0..1,temp=456,guild=!0}] sign_inicon 10
scoreboard players add @a[scores={sign_in=0..1,temp=456},tag=developer] sign_inicon 5
scoreboard players add @a[scores={sign_in=0..1,temp=456},tag=admin] sign_inicon 5
scoreboard players set @a[scores={sign_in=0..1,temp=456,deadproject=!0..1430}] deadproject 1430
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ scoreboard players add @s sign_inrewards 0
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ scoreboard players operation @s coin += @s sign_inicon
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ scoreboard players operation @s sign_inrewards = today sign_inrewards
execute @a[scores={sign_in=2,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=2,language=0,temp=456}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f§c签到失败！§f您今天已经签到了，明天再来试试吧。"}]}
execute @a[scores={sign_in=2,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=2,language=1,temp=456}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§f§cCheck in failed! §fYou've signed in today. Try again tomorrow."}]}
execute @a[scores={sign_in=2,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=2,language=2,temp=456}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f§c簽到失敗！§f您今天已經簽到了，明天再來試試吧。"}]}
execute @a[scores={sign_in=2,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=2,language=3,temp=456}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§f§cチェックイン失敗！§f今日はもうおチェックインになりましたから、明日またお試しください。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=1}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c龙息*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=2}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c钻石*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=3}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c线*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=4}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c鳞甲*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=5}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c幻翼膜*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=6}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c燧石*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=7}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c木炭*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=8}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c金粒*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=9}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c铁粒*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=10}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c附魔之瓶*6§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=11}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c海晶碎片*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=12}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c海晶砂粒*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=13}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c鹦鹉螺壳*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=14}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c烈焰棒*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=15}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c末影珍珠*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=16}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c潜影壳*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=17}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c恶魂之泪*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=18}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c粘液球*12§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=19}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c不死图腾*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=20}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c荧石粉*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=21}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c炸药*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=22}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c粘土*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=23}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c熟牛肉*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=24}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c蛋糕*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=25}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c海绵*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=26}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c糖*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=27}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c兔子脚*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=28}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c皮革*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=1}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cDragon's Breath*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=2}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cDiamond*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=3}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cString*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=4}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cScute*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=5}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cPhantom Membrane*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=6}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cFlint*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=7}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cCharcoal*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=8}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cGold Nugget*8§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=9}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cIron Nugget*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=10}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cBottle o' Enchanting*6§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=11}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cPrismarine Shard*16§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=12}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cPrismarine Crystals*16§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=13}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cNautilus Shell*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=14}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cBlaze Rod*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=15}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cEnder Pearl*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=16}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cShulker Shell*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=17}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cGhast Tear*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=18}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cSlimeball*12§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=19}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cTotem of Undying*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=20}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cGlowstone Dust*8§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=21}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cTNT*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=22}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cClay*16§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=23}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cCooked Beef*2§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=24}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cCake*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=25}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cSponge*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=26}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cSugar*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=27}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cRabbit's Foot*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=28}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cLeather*4§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=1}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c龍的吐息*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=2}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c鑽石*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=3}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c絲線*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=4}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c鱗甲*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=5}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c幻影薄膜*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=6}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c打火石*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=7}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c木炭*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=8}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c碎金塊*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=9}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c鐵粒*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=10}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c經驗藥水瓶*6§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=11}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c海磷碎片*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=12}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c海磷晶體*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=13}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c鸚鵡螺殼*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=14}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c烈焰棒*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=15}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c終界珍珠*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=16}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c界伏蚌殼*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=17}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c幽靈之淚*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=18}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c史萊姆球*12§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=19}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c不死圖騰*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=20}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c閃石塵*8§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=21}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c炸藥*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=22}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c黏土*16§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=23}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c烤牛肉*2§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=24}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c蛋糕*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=25}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c海綿*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=26}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c砂糖*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=27}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c兔子腳*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=28}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c皮革*4§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=1}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cドラゴンの息*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=2}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cダイヤモンド*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=3}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c糸*4§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=4}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c甲羅のかけら*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=5}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cファントムの皮膜*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=6}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c火打ち石*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=7}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c木炭*4§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=8}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c金の塊*8§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=9}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c鉄塊*8§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=10}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cエンチャントのビン*6§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=11}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c暗海晶の破片*16§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=12}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c海結晶*16§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=13}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cオウムガイの殻*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=14}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cブレイズ ロッド*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=15}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cエンダーパール*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=16}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cシュルカーの殻*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=17}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cガストの涙*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=18}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cスライムボール*12§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=19}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c不死のトーテム*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=20}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cグロウストーンダスト*8§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=21}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cTNT 火薬*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=22}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c粘土*16§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=23}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c調理した牛肉*2§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=24}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cケーキ*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=25}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cスポンジ*4§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=26}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c砂糖*4§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=27}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§cウサギの足*4§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=28}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c革*4§f] にサインします。"}]}
#因为特殊情况无法get签到奖励的
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=0,temp=456,sign_inrewards=0}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f签到成功！您获得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬币 §f。今日签到奖励 [§c煤炭*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=1,temp=456,sign_inrewards=0}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fOperation successful! You got §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"coin §f. Sign-in rewards today [§cCoal*1§f]."}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=2,temp=456,sign_inrewards=0}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f簽到成功！您獲得了 §e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚硬幣 §f。今日簽到獎勵 [§c煤塊*1§f] 。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={sign_in=0..1,language=3,temp=456,sign_inrewards=0}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fチェックイン成功！§e"},{"score":{"name":"@s","objective":"sign_inicon"}},{"text":"枚の硬貨 §fを獲得しました。今日はご褒美 [§c石炭*1§f] にサインします。"}]}
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=0}] ~ ~ ~ give @s coal 1 0
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=1}] ~ ~ ~ give @s dragon_breath 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=2}] ~ ~ ~ give @s diamond 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=3}] ~ ~ ~ give @s string 4
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=4}] ~ ~ ~ give @s turtle_shell_piece 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=5}] ~ ~ ~ give @s phantom_membrane 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=6}] ~ ~ ~ give @s flint 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=7}] ~ ~ ~ give @s coal 4 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=8}] ~ ~ ~ give @s gold_nugget 8
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=9}] ~ ~ ~ give @s iron_nugget 8
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=10}] ~ ~ ~ give @s experience_bottle 6
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=11}] ~ ~ ~ give @s prismarine_shard	16
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=12}] ~ ~ ~ give @s prismarine_crystals 16
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=13}] ~ ~ ~ give @s nautilus_shell 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=14}] ~ ~ ~ give @s blaze_rod 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=15}] ~ ~ ~ give @s ender_pearl 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=16}] ~ ~ ~ give @s shulker_shell 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=17}] ~ ~ ~ give @s ghast_tear 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=18}] ~ ~ ~ give @s slime_ball 12
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=19}] ~ ~ ~ give @s totem 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=20}] ~ ~ ~ give @s glowstone_dust 8
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=21}] ~ ~ ~ give @s tnt 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=22}] ~ ~ ~ give @s clay_ball 16
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=23}] ~ ~ ~ give @s cooked_beef 2
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=24}] ~ ~ ~ give @s cake 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=25}] ~ ~ ~ give @s sponge 1
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=26}] ~ ~ ~ give @s sugar 4
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=27}] ~ ~ ~ give @s rabbit_foot 4
execute @a[scores={sign_in=0..1,temp=456,sign_inrewards=28}] ~ ~ ~ give @s leather 4
scoreboard players random @a[scores={sign_in=0..1,temp=456}] sign_intext 1 340
#计算玩家的累计签到天数
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ scoreboard players add @s signdays 1
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={language=0}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f您已累计签到 §b"},{"score":{"name":"@s","objective":"signdays"}},{"text":"天 §r§f。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={language=1}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§f您已累计签到 §b"},{"score":{"name":"@s","objective":"signdays"}},{"text":"天 §r§f。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={language=2}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f您已累計簽到 §b"},{"score":{"name":"@s","objective":"signdays"}},{"text":"天 §r§f。"}]}
execute @a[scores={sign_in=0..1,temp=456}] ~ ~ ~ tellraw @s[scores={language=3}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§f您已累计签到 §b"},{"score":{"name":"@s","objective":"signdays"}},{"text":"天 §r§f。"}]}
scoreboard players set @a[scores={sign_in=0..1,temp=456}] sign_in 2
scoreboard players set @a[scores={sign_in=2,temp=456}] sign_inicon 0
scoreboard players reset @a[scores={temp=456}] temp