#supply1
execute @a[scores={temp=99999,supply1=0,supplyrandom=1},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=2},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=3},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=4},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=5},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=6},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=7},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=8},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=9},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=10},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=11},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=12},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=13},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=14},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=15},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=16},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 4 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=17},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=18},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=19},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=20},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=21},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=22},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=23},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 6 
execute @a[scores={temp=99999,supply1=0,supplyrandom=24},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=25},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=26},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=27},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=28},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=29},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=30},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=31},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=32},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 8 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=33},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=34},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=35},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=36},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=37},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=38},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=39},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=40},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=41},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=42},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=43},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=44},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=45},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=46},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=47},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=48},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 16 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=49},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=50},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=51},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=52},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=53},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=54},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=55},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=56},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=57},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=58},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=59},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=60},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=61},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=62},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=63},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=64},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concrete 32 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=65},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=66},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=67},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=68},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=69},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=70},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=71},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=72},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=73},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=74},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=75},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=76},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=77},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=78},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=79},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=80},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 4 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=81},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=82},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=83},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=84},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=85},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=86},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=87},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 6 
execute @a[scores={temp=99999,supply1=0,supplyrandom=88},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=89},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=90},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=91},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=92},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=93},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=94},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=95},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=96},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 8 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=97},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=98},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=99},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=100},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=101},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=102},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=103},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=104},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=105},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=106},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=107},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=108},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=109},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=110},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=111},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=112},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 16 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=113},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=114},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=115},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=116},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=117},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=118},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=119},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=120},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=121},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=122},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=123},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=124},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=125},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=126},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=127},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=128},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 concretepowder 32 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=129},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=130},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=131},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=132},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=133},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=134},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=135},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=136},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=137},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=138},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=139},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=140},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=141},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=142},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=143},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=144},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 4 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=145},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=146},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=147},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=148},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=149},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=150},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=151},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 6 
execute @a[scores={temp=99999,supply1=0,supplyrandom=152},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=153},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=154},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=155},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=156},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=157},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=158},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=159},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=160},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 8 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=161},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=162},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=163},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=164},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=165},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=166},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=167},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=168},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=169},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=170},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=171},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=172},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=173},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=174},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=175},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=176},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 16 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=177},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=178},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=179},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=180},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=181},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=182},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=183},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=184},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=185},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=186},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=187},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=188},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=189},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=190},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=191},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=192},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass 32 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=193},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=194},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=195},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=196},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=197},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=198},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=199},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=200},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=201},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=202},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=203},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=204},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=205},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=206},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=207},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=208},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 4 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=209},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=210},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=211},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=212},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=213},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=214},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=215},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 6 
execute @a[scores={temp=99999,supply1=0,supplyrandom=216},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=217},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=218},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=219},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=220},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=221},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=222},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=223},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=224},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 8 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=225},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=226},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=227},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=228},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=229},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=230},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=231},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=232},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=233},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=234},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=235},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=236},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=237},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=238},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=239},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=240},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 16 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=241},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=242},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=243},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=244},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=245},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=246},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=247},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=248},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=249},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=250},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=251},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=252},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=253},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=254},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=255},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=256},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_glass_pane 32 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=257},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=258},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=259},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=260},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=261},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=262},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=263},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=264},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=265},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=266},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=267},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=268},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=269},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=270},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=271},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=272},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 4 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=273},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=274},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=275},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=276},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=277},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=278},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=279},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 6 
execute @a[scores={temp=99999,supply1=0,supplyrandom=280},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=281},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=282},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=283},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=284},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=285},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=286},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=287},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=288},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 8 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=289},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=290},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=291},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=292},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=293},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=294},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=295},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=296},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=297},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=298},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=299},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=300},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=301},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=302},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=303},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=304},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 16 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=305},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=306},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 1
execute @a[scores={temp=99999,supply1=0,supplyrandom=307},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 2
execute @a[scores={temp=99999,supply1=0,supplyrandom=308},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 3
execute @a[scores={temp=99999,supply1=0,supplyrandom=309},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 4
execute @a[scores={temp=99999,supply1=0,supplyrandom=310},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 5
execute @a[scores={temp=99999,supply1=0,supplyrandom=311},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 6
execute @a[scores={temp=99999,supply1=0,supplyrandom=312},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 7
execute @a[scores={temp=99999,supply1=0,supplyrandom=313},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 8
execute @a[scores={temp=99999,supply1=0,supplyrandom=314},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 9
execute @a[scores={temp=99999,supply1=0,supplyrandom=315},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 10
execute @a[scores={temp=99999,supply1=0,supplyrandom=316},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 11
execute @a[scores={temp=99999,supply1=0,supplyrandom=317},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 12
execute @a[scores={temp=99999,supply1=0,supplyrandom=318},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 13
execute @a[scores={temp=99999,supply1=0,supplyrandom=319},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 14
execute @a[scores={temp=99999,supply1=0,supplyrandom=320},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 stained_hardened_clay 32 15
execute @a[scores={temp=99999,supply1=0,supplyrandom=321},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 white_glazed_terracotta 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=322},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 white_glazed_terracotta 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=323},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 white_glazed_terracotta 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=324},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 white_glazed_terracotta 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=325},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=326},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=327},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=328},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 32 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=325},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 4 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=326},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 8 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=327},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 16 0
execute @a[scores={temp=99999,supply1=0,supplyrandom=328},tag=admin] ~ ~ ~ replaceitem block ~ ~ ~ slot.container 0 orange_glazed_terracotta 32 0