#getinfo
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info1] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info2] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info3] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info4] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info5] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info6] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info7] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info8] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info9] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info10] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info11] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info12] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info13] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info14] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info15] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info16] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info17] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info18] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info19] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info20] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info21] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info22] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info23] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info24] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info25] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info26] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info27] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info28] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info29] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info30] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info31] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info32] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info33] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info34] ~ ~ ~ function media/devtool/info
execute @a[tag=infomassage] ~ ~ ~ execute @a[tag=info35] ~ ~ ~ function media/devtool/info