#license
execute @e[scores={license=0,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f已自动为您标记所有者。"}]}
execute @e[scores={license=0,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fThe owner has been automatically marked for you."}]}
execute @e[scores={license=0,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f已自動為您標記所有者。"}]}
execute @e[scores={license=0,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§f所有者を自動的にマークしました。"}]}
execute @e[scores={license=0,typeid=128},type=minecraft:armor_stand] ~ ~ ~ scoreboard players set LICENSE version 1
execute @a[tag=owner,scores={login=4},tag=loginsuccess] ~ ~ ~ execute @e[scores={license=1,typeid=128},type=minecraft:armor_stand] ~ ~ ~ scoreboard players set LICENSE version 2
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§l§c项目最新内容您需要访问 xiaozhiyuqwq.top 与 skyblock.xiaozhiyuqwq.top ，如有协议更新时，以网站版本为标准。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f项目采用 GPL3.0 协议开源，请遵守开源协议使用。您必须保留项目中项目标识、开发者名称及项目主页链接字样，否则您不可以使用该项目。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§f同时，在您使用项目的时候，也必须要遵守来自 MOJANG 团队所制订的 [MINECRAFT 最终用户许可协议] ，该协议您可以访问 MOJANG 团队官方网站 (https://www.mojang.com/) 或者是访问 https://account.mojang.com/documents/minecraft_eula 查询。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§l§b联系方式 GitHub个人主页 §r§fhttps://github.com/xiaozhiyuqwq §l§bGitHub项目主页 §r§fhttps://github.com/xiaozhiyuqwq/Skyblock-for-Server §l§bGitee个人主页 §r§fhttps://gitee.com/xiaozhiyuqwq §l§bGitee项目主页 §r§fhttps://gitee.com/xiaozhiyuqwq/Skyblock-for-Server §l§b哔哩哔哩主页 §r§fhttps://space.bilibili.com/437306982 §l§b个人站点 §r§fhttps://xiaozhiyuqwq.top §l§b个人邮箱 §r§fxhduoduobaby@qq.com hi@xiaozhiyuqwq.top §l§b。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§l§c在使用本项目前，敬请您仔细阅读各项使用条款。您对本项目的使用，将被视为您自愿承诺接受本声明的约束。如果您对本使用条款的内容不能接受，您应当立即停止使用本项目并迅速离开及删除！"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=0},tag=owner] {"rawtext":[{"text":"§l§e空岛生存§f>>§l§a你和我说他的可爱，你和我说他的好看。恍惚间窥见在樱花树下，铁道边，一对少男少女彼此走着，风起花落拂过他们脸颊。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§cFor the latest content of the project, you need to visit xiaozhiyuqwq.top and skyblock.xiaozhiyuqwq.top. If there is an agreement to update, the website version shall be the standard."}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fThe project adopts GPL3.0 open source protocol, please follow the open source protocol. You must keep the project ID, developer name and project home page link in the project, otherwise you can't use the project."}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fAt the same time, when you use the project, you must comply with the Minecraft End-User License Agreement from the Mojang team, under which you can access the Mojang team's official website (https://www.mojang.com/) or access https://account.mojang.com/documents/minecraft_eula queries"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§bContact GitHub Personal homepage §r§fhttps://github.com/xiaozhiyuqwq §l§bGitHub Project Home §r§fhttps://github.com/xiaozhiyuqwq/Skyblock-for-Server §l§bGitee Personal homepage §r§fhttps://gitee.com/xiaozhiyuqwq §l§bGitee Project Home §r§fhttps://gitee.com/xiaozhiyuqwq/Skyblock-for-Server §l§bBilibili §r§fhttps://space.bilibili.com/437306982 §l§bWebside §r§fhttps://xiaozhiyuqwq.top §l§bE-mail §r§fxhduoduobaby@qq.com hi@xiaozhiyuqwq.top §l§b."}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=1},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§cAt present, please read the terms of use carefully. Your use of this project will be deemed as your voluntary commitment to be bound by this statement. If you can't accept the content of the terms of use, you should immediately stop using the project and quickly leave and delete it!"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§l§c項目最新內容您需要訪問xiaozhiyuqwq.top與skyblock.xiaozhiyuqwq.top，如有協定更新時，以網站版本為標準。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f項目採用 GPL3.0 協定開源，請遵守開源協定使用。您必須保留項目中項目標識、開發者名稱及項目主頁連結字樣，否則您不可以使用該項目。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§r§f同時，在您使用項目的時候，也必須要遵守來自MOJANG團隊所制訂的[MINECRAFT使用者授權合約]，該協定您可以訪問 MOJANG 團隊官方網站（https://www.mojang.com/）或者是訪問 https://account.mojang.com/documents/minecraft_eula 査詢。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§l§b聯繫方式 GitHub個人主頁 §r§fhttps://github.com/xiaozhiyuqwq §l§bGitHub項目主頁 §r§fhttps://github.com/xiaozhiyuqwq/Skyblock-for-Server §l§bGitee個人主頁 §r§fhttps://gitee.com/xiaozhiyuqwq §l§bGitee項目主頁 §r§fhttps://gitee.com/xiaozhiyuqwq/Skyblock-for-Server §l§b嗶哩嗶哩主頁 §r§fhttps://space.bilibili.com/437306982 §l§b個人網站 §r§fhttps://xiaozhiyuqwq.top §l§b個人郵箱 §r§fxhduoduobaby@qq.com hi@xiaozhiyuqwq.top §l§b。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=2},tag=owner] {"rawtext":[{"text":"§l§e空島生存§f>>§l§c在使用本項現時，敬請您仔細閱讀各項使用條款。您對本項目的使用，將被視為您自願承諾接受本聲明的約束。如果您對本使用條款的內容不能接受，您應當立即停止使用本項目並迅速離開及删除！"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§cプロジェクトの最新の内容は xiaozhiyuqwq.top と skyblock.xiaozhiyuqwq.top にアクセスする必要があります。もしプロトコルが更新されたら、ウェブサイトのバージョンを基準としています。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fプロジェクトはGPL 3.0プロトコルでオープンソースを採用していますので、オープンソースプロトコルを守ってご利用ください。プロジェクトのプロジェクト識別、開発者名、およびプロジェクトのホームページリンクの文字を残してください。でないと、このプロジェクトは使えません。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§fまた、プロジェクトを使用する場合は、MOJANGチームから作成された「MINECRAFT最終ユーザー許可協議」を遵守しなければなりません。このプロトコルはMOJANGチームの公式サイト（https://www.mojang.com/）にアクセスするか、 https://account.mojang.com/documents/minecraft_eula にアクセスすることができます。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§b連絡 GitHubホームページ §r§fhttps://github.com/xiaozhiyuqwq §l§bGitHubプロジェクトホームページ §r§fhttps://github.com/xiaozhiyuqwq/Skyblock-for-Server §l§bGiteeホームページ §r§fhttps://gitee.com/xiaozhiyuqwq §l§bGiteeプロジェクトホームページ §r§fhttps://gitee.com/xiaozhiyuqwq/Skyblock-for-Server §l§bBilibili §r§fhttps://space.bilibili.com/437306982 §l§bWebside §r§fhttps://xiaozhiyuqwq.top §l§bE-mail §r§fxhduoduobaby@qq.com hi@xiaozhiyuqwq.top §l§b。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tellraw @a[scores={language=3},tag=owner] {"rawtext":[{"text":"§l§eSkyBlock§f>>§l§c本項を使用していますので、各利用規約をよくお読みください。本プロジェクトの使用は、あなたが自ら承諾したものと見なされます。本利用規約の内容が受け入れられない場合は、直ちに本プロジェクトの使用を中止し、速やかに退去し、削除しなければなりません。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ titleraw @a[scores={language=0},tag=owner] title {"rawtext":[{"text":"§r§f请阅读授权协议"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ titleraw @a[scores={language=1},tag=owner] title {"rawtext":[{"text":"§r§fPlease read the license agreement"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ titleraw @a[scores={language=2},tag=owner] title {"rawtext":[{"text":"§r§f請閱讀授權協議"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ tag @a[tag=owner] add git
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ titleraw @a[scores={language=3},tag=owner] title {"rawtext":[{"text":"§r§fライセンス契約を読んでください。"}]}
execute @e[scores={license=2,typeid=128},type=minecraft:armor_stand] ~ ~ ~ scoreboard players set LICENSE version 3
tag @a[tag=owner] add LICENSEget