#success 注册成功的提示
execute @e[type=armor_stand,scores={typeid=128,version=0}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard objectives add enrolltitle dummy
execute @e[type=armor_stand,scores={typeid=128,version=0}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard objectives add enrolltitle1 dummy
execute @e[type=armor_stand,scores={typeid=128,version=0}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard players add @s enrolltitle 0
execute @e[type=armor_stand,scores={typeid=128,version=0}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard players add @s enrolltitle1 0
#gird
execute @e[type=armor_stand,scores={typeid=128,version=2}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard objectives add enrolltitle dummy
execute @e[type=armor_stand,scores={typeid=128,version=2}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard objectives add enrolltitle1 dummy
execute @e[type=armor_stand,scores={typeid=128,version=2}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard players add @s enrolltitle 0
execute @e[type=armor_stand,scores={typeid=128,version=2}] ~ ~ ~ execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ scoreboard players add @s enrolltitle1 0
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=0..}] ~ ~ ~ scoreboard players add @s enrolltitle 1
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=0,version=1}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感谢您选择 空岛生存-服务端版本 ！\n当前正在运行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" BETA]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=0,version=2}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感谢您选择 空岛生存-服务端版本 ！\n当前正在运行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" RELEASE]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=0,version=3}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感谢您选择 空岛生存-服务端版本 ！\n当前正在运行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEMO]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=0,version=4}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感谢您选择 空岛生存-服务端版本 ！\n当前正在运行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEVELOP]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=0,version=5}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感谢您选择 空岛生存-服务端版本 ！\n当前正在运行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" SNAPSHOT]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=1,version=1}] subtitle {"rawtext":[{"text":"§fHello!§6 "},{"selector":"@s"},{"text":" §f！\nThank you for choosing Skyblock-for-Server !\nCurrently running §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" BETA]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=1,version=2}] subtitle {"rawtext":[{"text":"§fHello!§6 "},{"selector":"@s"},{"text":" §f！\nThank you for choosing Skyblock-for-Server !\nCurrently running §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" RELEASE]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=1,version=3}] subtitle {"rawtext":[{"text":"§fHello!§6 "},{"selector":"@s"},{"text":" §f！\nThank you for choosing Skyblock-for-Server !\nCurrently running §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEMO]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=1,version=4}] subtitle {"rawtext":[{"text":"§fHello!§6 "},{"selector":"@s"},{"text":" §f！\nThank you for choosing Skyblock-for-Server !\nCurrently running §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEVELOP]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=1,version=5}] subtitle {"rawtext":[{"text":"§fHello!§6 "},{"selector":"@s"},{"text":" §f！\nThank you for choosing Skyblock-for-Server !\nCurrently running §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" SNAPSHOT]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=2,version=1}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感謝您選擇 空島生存-伺服器版本 ！\n當前正在運行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" BETA]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=2,version=2}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感謝您選擇 空島生存-伺服器版本 ！\n當前正在運行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" RELEASE]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=2,version=3}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感謝您選擇 空島生存-伺服器版本 ！\n當前正在運行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEMO]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=2,version=4}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感謝您選擇 空島生存-伺服器版本 ！\n當前正在運行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEVELOP]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=2,version=5}] subtitle {"rawtext":[{"text":"§f嘿！§6 "},{"selector":"@s"},{"text":" §f！\n感謝您選擇 空島生存-伺服器版本 ！\n當前正在運行 §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" SNAPSHOT]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=3,version=1}] subtitle {"rawtext":[{"text":"§fこんにちは！§6 "},{"selector":"@s"},{"text":" §f！\nSkyblock-for-Serverをお選びいただきありがとうございます!\nVersion §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" BETA]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=3,version=2}] subtitle {"rawtext":[{"text":"§fこんにちは！§6 "},{"selector":"@s"},{"text":" §f！\nSkyblock-for-Serverをお選びいただきありがとうございます!\nVersion §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" RELEASE]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=3,version=3}] subtitle {"rawtext":[{"text":"§fこんにちは！§6 "},{"selector":"@s"},{"text":" §f！\nSkyblock-for-Serverをお選びいただきありがとうございます!\nVersion §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEMO]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=3,version=4}] subtitle {"rawtext":[{"text":"§fこんにちは！§6 "},{"selector":"@s"},{"text":" §f！\nSkyblock-for-Serverをお選びいただきありがとうございます!\nVersion §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" DEVELOP]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ titleraw @s[scores={language=3,version=5}] subtitle {"rawtext":[{"text":"§fこんにちは！§6 "},{"selector":"@s"},{"text":" §f！\nSkyblock-for-Serverをお選びいただきありがとうございます!\nVersion §c["},{"score":{"name":"upyear","objective":"version"}},{"text":"."},{"score":{"name":"upmouth","objective":"version"}},{"text":"-"},{"score":{"name":"mainver","objective":"version"}},{"text":"."},{"score":{"name":"branchesver","objective":"version"}},{"text":" SNAPSHOT]"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=101..,enrolltitle1=0}] ~ ~ ~ scoreboard players set @s enrolltitle1 1
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ titleraw @s[scores={language=0}] subtitle {"rawtext":[{"text":"§f您可以访问 Github 与 Gitee\n搜索 xiaozhiyuqwq\n查看我们开源的项目！"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ titleraw @s[scores={language=1}] subtitle {"rawtext":[{"text":"§fYou can access GitHub and Gitee\nSearch xiaozhiyuqwq\nCheck out our open source projects!"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ titleraw @s[scores={language=2}] subtitle {"rawtext":[{"text":"§f您可以訪問Github與Gitee\n蒐索 xiaozhiyuqwq\n查看我們開源的項目！"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ titleraw @s[scores={language=3}] subtitle {"rawtext":[{"text":"§fGithubとGiteeにアクセスできます\n検索 xiaozhiyuqwq\nオープンソースのプロジェクトを表示します!"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=201..,enrolltitle1=1}] ~ ~ ~ scoreboard players set @s enrolltitle1 2
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ titleraw @s[scores={language=0}] subtitle {"rawtext":[{"text":"§f如果您在使用过程中发现漏洞\n您可以通过 Github 与 Gitee\n提交 issues 以联系开发者"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ titleraw @s[scores={language=1}] subtitle {"rawtext":[{"text":"§fIf you find bugs during use\nYou can use GitHub and Gitee\nSubmit issues to contact the developer"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ titleraw @s[scores={language=2}] subtitle {"rawtext":[{"text":"§f如果您在使用過程中發現漏洞\n您可以通过 Github 与 Gitee\n提交issues以聯系開發者"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ titleraw @s[scores={language=3}] subtitle {"rawtext":[{"text":"§f使用中にbugsを見つけた場合\nGithubとGiteeで\n開発者に連絡するissuesを送信"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=301..,enrolltitle1=2}] ~ ~ ~ scoreboard players set @s enrolltitle1 3
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ titleraw @s[scores={language=0}] subtitle {"rawtext":[{"text":"§f开发者：祉语(xiaozhiyuqwq)\n个人主页：xiaozhiyuqwq.top\nB站ID：祉语(uid:437306982)"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ titleraw @s[scores={language=1}] subtitle {"rawtext":[{"text":"§fDeveloper xiaozhiyuqwq\nWebside xiaozhiyuqwq.top\nBilibiliID 祉语(uid:437306982)"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ titleraw @s[scores={language=2}] subtitle {"rawtext":[{"text":"§f開發者：祉語(xiaozhiyuqwq)\n個人主頁：xiaozhiyuqwq.top\nBilibiliID：祉语(uid:437306982)"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ titleraw @s[scores={language=3}] subtitle {"rawtext":[{"text":"§f開発者：xiaozhiyuqwq\nWebside：xiaozhiyuqwq.top\nBilibiliID：祉语(uid:437306982)"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=401..,enrolltitle1=3}] ~ ~ ~ scoreboard players set @s enrolltitle1 4
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ titleraw @s[scores={language=0}] subtitle {"rawtext":[{"text":"§f空岛生存-服务端版本\n项目官网\nskyblock.xiaozhiyuqwq.top"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ titleraw @s[scores={language=1}] subtitle {"rawtext":[{"text":"§fSkyblock-for-Server\nProject official website\nskyblock.xiaozhiyuqwq.top"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ titleraw @s[scores={language=2}] subtitle {"rawtext":[{"text":"§f空島生存-伺服器版本\n項目官網\nskyblock.xiaozhiyuqwq.top"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ titleraw @s[scores={language=3}] subtitle {"rawtext":[{"text":"§fSkyblock-for-Server\nプロジェクト公式サイト\nskyblock.xiaozhiyuqwq.top"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=501..,enrolltitle1=4}] ~ ~ ~ scoreboard players set @s enrolltitle1 5
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ titleraw @s title {"rawtext":[{"text":"§l"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ titleraw @s[scores={language=0}] subtitle {"rawtext":[{"text":"§6游玩愉快！\n§e\n§b何当共剪西窗烛，却话巴山夜雨时。"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ titleraw @s[scores={language=1}] subtitle {"rawtext":[{"text":"§6Have a good time!\n§e\n§b何当共剪西窗烛，却话巴山夜雨时。"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ titleraw @s[scores={language=2}] subtitle {"rawtext":[{"text":"§6遊玩愉快！\n§e\n§b何當共剪西窗燭，卻話巴山夜雨時。"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ titleraw @s[scores={language=3}] subtitle {"rawtext":[{"text":"§6楽しんでね！\n§e\n§b何当共剪西窗烛，却话巴山夜雨时。"}]}
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=5}] ~ ~ ~ scoreboard players set @s enrolltitle1 6
execute @a[tag=enrollsuccess,tag=!enrollsuccess1,scores={enrolltitle=601..,enrolltitle1=6}] ~ ~ ~ tag @s add enrollsuccess1
execute @a[tag=enrollsuccess,tag=!enrollsuccess1] ~ ~ ~ execute @a[tag=enrollsuccess,tag=enrollsuccess1] ~ ~ ~ tag @s add enrollsuccess2
execute @a[tag=enrollsuccess,tag=enrollsuccess1,tag=!enrollsuccess2] ~ ~ ~ scoreboard objectives remove enrolltitle
execute @a[tag=enrollsuccess,tag=enrollsuccess1,tag=!enrollsuccess2] ~ ~ ~ scoreboard objectives remove enrolltitle1
execute @a[tag=enrollsuccess,tag=enrollsuccess1,tag=!enrollsuccess2] ~ ~ ~ tag @s add enrollsuccess2
execute @a[tag=enrollsuccess2] ~ ~ ~ tag @s remove enrollsuccess
execute @a[tag=enrollsuccess2] ~ ~ ~ tag @s remove enrollsuccess1
execute @a[tag=enrollsuccess2] ~ ~ ~ tag @s remove enrollsuccess2