#islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~1 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~2 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~3 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~4 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~5 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~6 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~7 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~8 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~9 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~10 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~11 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~12 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~13 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~14 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~15 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~16 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~17 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~18 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~19 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~20 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~21 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~22 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~23 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~24 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~25 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~26 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~27 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~28 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~29 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~30 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~31 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~32 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~33 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~34 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~35 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~36 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~37 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~38 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~39 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~40 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~41 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~42 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~43 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~44 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~45 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~46 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~47 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~48 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~49 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~50 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~51 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~52 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~53 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~54 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~55 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~56 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~57 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~58 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~59 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~60 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~61 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~62 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~63 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~64 1 ~ deny 0 tag @s add islandbarrier





execute @a ~ ~ ~ detect ~-1 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-2 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-3 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-4 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-5 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-6 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-7 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-8 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-9 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-10 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-11 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-12 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-13 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-14 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-15 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-16 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-17 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-18 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-19 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-20 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-21 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-22 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-23 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-24 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-25 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-26 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-27 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-28 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-29 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-30 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-31 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-32 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-33 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-34 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-35 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-36 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-37 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-38 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-39 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-40 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-41 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-42 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-43 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-44 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-45 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-46 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-47 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-48 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-49 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-50 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-51 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-52 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-53 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-54 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-55 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-56 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-57 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-58 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-59 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-60 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-61 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-62 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-63 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-64 1 ~ deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~1 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~2 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~3 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~4 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~5 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~6 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~7 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~8 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~9 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~10 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~11 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~12 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~13 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~14 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~15 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~16 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~17 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~18 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~19 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~20 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~21 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~22 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~23 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~24 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~25 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~26 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~27 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~28 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~29 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~30 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~31 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~32 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~33 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~34 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~35 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~36 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~37 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~38 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~39 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~40 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~41 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~42 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~43 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~44 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~45 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~46 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~47 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~48 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~49 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~50 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~51 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~52 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~53 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~54 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~55 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~56 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~57 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~58 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~59 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~60 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~61 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~62 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~63 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~64 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-1 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-2 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-3 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-4 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-5 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-6 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-7 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-8 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-9 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-10 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-11 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-12 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-13 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-14 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-15 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-16 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-17 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-18 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-19 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-20 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-21 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-22 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-23 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-24 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-25 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-26 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-27 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-28 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-29 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-30 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-31 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-32 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-33 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-34 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-35 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-36 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-37 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-38 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-39 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-40 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-41 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-42 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-43 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-44 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-45 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-46 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-47 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-48 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-49 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-50 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-51 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-52 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-53 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-54 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-55 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-56 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-57 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-58 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-59 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-60 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-61 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-62 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-63 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 1 ~-64 deny 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~1 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~2 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~3 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~4 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~5 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~6 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~7 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~8 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~9 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~10 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~11 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~12 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~13 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~14 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~15 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~16 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-1 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-2 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-3 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-4 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-5 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-6 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-7 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-8 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-9 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-10 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-11 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-12 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-13 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-14 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-15 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-16 253 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~1 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~2 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~3 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~4 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~5 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~6 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~7 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~8 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~9 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~10 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~11 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~12 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~13 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~14 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~15 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~16 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-1 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-2 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-3 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-4 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-5 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-6 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-7 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-8 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-9 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-10 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-11 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-12 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-13 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-14 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-15 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 253 ~-16 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~1 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~2 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~3 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~4 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~5 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~6 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~7 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~8 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~9 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~10 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~11 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~12 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~13 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~14 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~15 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~16 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-1 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-2 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-3 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-4 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-5 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-6 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-7 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-8 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-9 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-10 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-11 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-12 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-13 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-14 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-15 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~-16 0 ~ bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~1 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~2 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~3 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~4 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~5 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~6 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~7 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~8 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~9 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~10 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~11 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~12 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~13 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~14 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~15 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~16 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-1 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-2 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-3 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-4 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-5 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-6 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-7 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-8 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-9 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-10 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-11 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-12 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-13 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-14 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-15 bedrock 0 tag @s add islandbarrier
execute @a ~ ~ ~ detect ~ 0 ~-16 bedrock 0 tag @s add islandbarrier
execute @a[tag=islandbarrier,scores={actionbar=!0..39}] ~ ~ ~ scoreboard players set @s actionbar 40
tag @a[tag=!islandbarrier,tag=islandbarriertellraw] remove islandbarriertellraw
execute @a[tag=islandbarrier,tag=!islandbarriertellraw] ~ ~ ~ tellraw @s[scores={language=0}] {"rawtext":[{"text":"§l§e空岛生存§f>>§r§7您已经来到了岛屿边界！ 您将无法通过边界墙，同时，您也无法破坏边界墙。"}]}
execute @a[tag=islandbarrier,tag=!islandbarriertellraw] ~ ~ ~ tellraw @s[scores={language=1}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§7You have come to the boundary of the island! You will not be able to pass through the boundary wall, and you will not be able to break it."}]}
execute @a[tag=islandbarrier,tag=!islandbarriertellraw] ~ ~ ~ tellraw @s[scores={language=2}] {"rawtext":[{"text":"§l§e空島生存§f>>§r§7您已經來到了島嶼邊界！ 您將無法通過邊界牆，同時，您也無法破壞邊界牆。"}]}
execute @a[tag=islandbarrier,tag=!islandbarriertellraw] ~ ~ ~ tellraw @s[scores={language=3}] {"rawtext":[{"text":"§l§eSkyBlock§f>>§r§7島の境界に来ました。境界壁を通ることはできません。同時に境界壁を破壊することもできません。"}]}
execute @a ~ ~ ~ titleraw @s[scores={language=0,actionbar=40}] actionbar {"rawtext":[{"text":"§l§f您好！ §6您已到达岛屿边界！"}]}
execute @a ~ ~ ~ titleraw @s[scores={language=1,actionbar=40}] actionbar {"rawtext":[{"text":"§fHello! §6You have reached the boundary of the island!"}]}
execute @a ~ ~ ~ titleraw @s[scores={language=2,actionbar=40}] actionbar {"rawtext":[{"text":"§l§f您好！ §6您已到達島嶼邊界！"}]}
execute @a ~ ~ ~ titleraw @s[scores={language=3,actionbar=40}] actionbar {"rawtext":[{"text":"§l§fこんにちは！ §6島の境界に着きました。"}]}
tag @a[tag=islandbarrier,tag=!islandbarriertellraw] add islandbarriertellraw
execute @a[tag=islandbarrier] ~ ~ ~ tag @s remove islandbarrier